// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJR8pvTc22CUkzSNttkI3kFANUtI9Qv6A',
    appId: '1:17568864626:web:62cdd7e6c9232ef2b9e5eb',
    messagingSenderId: '17568864626',
    projectId: 'messenger-54b1a',
    authDomain: 'messenger-54b1a.firebaseapp.com',
    storageBucket: 'messenger-54b1a.appspot.com',
    measurementId: 'G-82KJQNRVT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm3x2f1PQmkqoxcQBhqJ_Ap77nA6HUSW8',
    appId: '1:17568864626:android:e1d5f132a125386ab9e5eb',
    messagingSenderId: '17568864626',
    projectId: 'messenger-54b1a',
    storageBucket: 'messenger-54b1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9TO50USsjhrcIjTx4bOwEb0PlkmpgieA',
    appId: '1:17568864626:ios:52ba91cf49155284b9e5eb',
    messagingSenderId: '17568864626',
    projectId: 'messenger-54b1a',
    storageBucket: 'messenger-54b1a.appspot.com',
    iosClientId: '17568864626-6rsfmpgmfqfk7f9ees25dr4nur8l4nnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
